title: sohaib.eu
author:
  name: Sohaib E.B.
  email: sohaib@sohaib.eu
#description: > # this means to ignore newlines until "show_excerpts:"

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: " %d %-b, %Y"

  # Social Links Footer
  social_links:
    github:  sohaibeb

    # Mastodon instances
    # mastodon:
    # - username: sohaib
    #   instance: mastodon.social

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
